// <auto-generated />
using System;
using KennelPro.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KennelPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802171138_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("DogTitle", b =>
                {
                    b.Property<Guid>("DogsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TitlesId")
                        .HasColumnType("TEXT");

                    b.HasKey("DogsId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("DogTitle");
                });

            modelBuilder.Entity("KennelPro.Models.Authentication.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KennelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KennelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KennelPro.Models.Authentication.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("KennelPro.Models.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("KennelPro.Models.Documents.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AwardedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("KennelPro.Models.Dogs.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("KennelPro.Models.Dogs.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BreedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KennelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PedigreeNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("KennelId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("KennelPro.Models.Kennels.Kennel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kennels");
                });

            modelBuilder.Entity("KennelPro.Models.Litters.Litter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FatherDogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MotherDogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FatherDogId");

                    b.HasIndex("MotherDogId");

                    b.ToTable("Litters");
                });

            modelBuilder.Entity("KennelPro.Models.Litters.Puppy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LitterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LitterId");

                    b.ToTable("Puppies");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllergyInfo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.ParasiteTreatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextTreatmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("ParasiteTreatments");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.Vaccination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevaccinationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VaccinationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("KennelPro.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("KennelPro.Models.Reproduction.HeatCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextCycleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("HeatCycles");
                });

            modelBuilder.Entity("KennelPro.Models.Reproduction.Mating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FemaleDogId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaleDogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("FemaleDogId");

                    b.HasIndex("MaleDogId");

                    b.ToTable("Matings");
                });

            modelBuilder.Entity("DogTitle", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KennelPro.Models.Documents.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KennelPro.Models.Authentication.User", b =>
                {
                    b.HasOne("KennelPro.Models.Kennels.Kennel", "Kennel")
                        .WithMany("Users")
                        .HasForeignKey("KennelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kennel");
                });

            modelBuilder.Entity("KennelPro.Models.Documents.Document", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany("Documents")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Dogs.Dog", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Breed", "Breed")
                        .WithMany("Dogs")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KennelPro.Models.Kennels.Kennel", "Kennel")
                        .WithMany("Dogs")
                        .HasForeignKey("KennelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breed");

                    b.Navigation("Kennel");
                });

            modelBuilder.Entity("KennelPro.Models.Litters.Litter", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "FatherDog")
                        .WithMany("LittersAsFather")
                        .HasForeignKey("FatherDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KennelPro.Models.Dogs.Dog", "MotherDog")
                        .WithMany("LittersAsMother")
                        .HasForeignKey("MotherDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FatherDog");

                    b.Navigation("MotherDog");
                });

            modelBuilder.Entity("KennelPro.Models.Litters.Puppy", b =>
                {
                    b.HasOne("KennelPro.Models.Litters.Litter", "Litter")
                        .WithMany("Puppies")
                        .HasForeignKey("LitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Litter");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.Disease", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.MedicalRecord", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.Medication", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.ParasiteTreatment", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Medical.Vaccination", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Notifications.Notification", b =>
                {
                    b.HasOne("KennelPro.Models.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KennelPro.Models.Reproduction.HeatCycle", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", "Dog")
                        .WithMany("HeatCycles")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dog");
                });

            modelBuilder.Entity("KennelPro.Models.Reproduction.Mating", b =>
                {
                    b.HasOne("KennelPro.Models.Dogs.Dog", null)
                        .WithMany("Matings")
                        .HasForeignKey("DogId");

                    b.HasOne("KennelPro.Models.Dogs.Dog", "FemaleDog")
                        .WithMany()
                        .HasForeignKey("FemaleDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KennelPro.Models.Dogs.Dog", "MaleDog")
                        .WithMany()
                        .HasForeignKey("MaleDogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FemaleDog");

                    b.Navigation("MaleDog");
                });

            modelBuilder.Entity("KennelPro.Models.Dogs.Breed", b =>
                {
                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("KennelPro.Models.Dogs.Dog", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("HeatCycles");

                    b.Navigation("LittersAsFather");

                    b.Navigation("LittersAsMother");

                    b.Navigation("Matings");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("KennelPro.Models.Kennels.Kennel", b =>
                {
                    b.Navigation("Dogs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KennelPro.Models.Litters.Litter", b =>
                {
                    b.Navigation("Puppies");
                });
#pragma warning restore 612, 618
        }
    }
}
