// <auto-generated />
using KennelPro.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KennelPro.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260808170000_AddMedicalDetails")]
partial class AddMedicalDetails
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.10");
    }
}
